<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="logging" nsURI="org.eclipse.jwt.sample.logging" nsPrefix="logging">
  <eClassifiers xsi:type="ecore:EClass" name="Logging" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loggingLevel" eType="#//LoggingLevels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoggingLevels">
    <eLiterals name="INFO" value="1"/>
    <eLiterals name="DEBUG" value="2"/>
    <eLiterals name="SEVERE" value="3"/>
  </eClassifiers>
</ecore:EPackage>
