<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="org.js.model.process.model" nsPrefix="model">
  <eSubpackages name="acmref" nsURI="org.js.model.proces.model.acmref" nsPrefix="acmref">
    <eClassifiers xsi:type="ecore:EClass" name="ACMConnector" eSuperTypes="org.eclipse.jwt.conf#//AspectInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ACMRef" eType="ecore:EClass ../../org.js.model.rbac/src/main/model/rbac.ecore#//AccessControlModel"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="roleref" nsURI="org.js.model.process.model.roleref" nsPrefix="roleref">
    <eClassifiers xsi:type="ecore:EClass" name="RoleConnector" eSuperTypes="org.eclipse.jwt.conf#//AspectInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="roleref" eType="ecore:EClass ../../org.js.model.rbac/src/main/model/rbac.ecore#//Role"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
