<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registereddynamicaspect" nsURI="org.eclipse.jwt.sample.registereddynamicaspect"
    nsPrefix="registereddynamicaspect">
  <eClassifiers xsi:type="ecore:EClass" name="SampleRegisteredDynamicAspect" eSuperTypes="org.eclipse.jwt.conf#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleintprop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampleactionref" eType="ecore:EClass org.eclipse.jwt/processes#//Action"/>
  </eClassifiers>
</ecore:EPackage>
